
version: '3.6'

services:
  # RDB
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  # HASURA
  graphql-engine:
    container_name: hasura
    build:
      context: ./hasura
      dockerfile: ./Dockerfile
      args:
        - DATABASE_URL=postgres://postgres:postgrespassword@postgres:5432/postgres
        - LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

  # ACTIONS
  actions:
    container_name: actions
    build:
      context: ./actions
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./actions:/usr/src/app
    environment:
      ENVIRONMENT: development
      PORT: 9000
      BIND_HOST: 0.0.0.0

volumes:
  db_data: